# -*- coding: utf-8 -*-
"""Extension manuelle du vocabulaire (voir note dans notes-projet.md :
l'accès réseau de cette session ne permettait pas de récupérer un vrai
dictionnaire ouvert type Lexique383 aujourd'hui — mots ajoutés à la
main, vérifiés, en attendant une vraie intégration de dictionnaire)."""

EXPANSION = [
    # animaux
    ("OURS", "Il hiberne tout l'hiver"),
    ("LOUP", "Il chasse en meute"),
    ("RENARD", "Rusé comme lui"),
    ("LAPIN", "Il a de longues oreilles"),
    ("SOURIS", "Petit rongeur qui aime le fromage"),
    ("OISEAU", "Il a des ailes et un bec"),
    ("POISSON", "Il vit dans l'eau et respire par des branchies"),
    ("SERPENT", "Reptile sans pattes"),
    ("ARAIGNEE", "Elle tisse une toile"),
    ("ABEILLE", "Elle produit du miel"),
    ("MOUCHE", "Petit insecte qui bourdonne"),
    ("PAPILLON", "Il sort de sa chrysalide"),
    ("TIGRE", "Grand félin rayé"),
    ("LION", "Roi de la savane"),
    ("SINGE", "Il aime grimper aux arbres"),
    ("VACHE", "Elle donne du lait"),
    ("COCHON", "Animal de ferme rose"),
    ("MOUTON", "Il donne de la laine"),
    ("CHEVAL", "On le monte pour se déplacer"),
    ("POULE", "Elle pond des œufs"),
    # corps
    ("TETE", "Elle contient le cerveau"),
    ("MAIN", "Elle a cinq doigts"),
    ("PIED", "On marche avec"),
    ("BRAS", "Il relie l'épaule à la main"),
    ("JAMBE", "Elle permet de marcher"),
    ("DOS", "Partie arrière du corps"),
    ("VENTRE", "Il gargouille quand on a faim"),
    ("COEUR", "Il bat dans la poitrine"),
    ("OEIL", "Il permet de voir"),
    ("BOUCHE", "Elle sert à parler et manger"),
    ("NEZ", "Il sent les odeurs"),
    ("DENT", "On la brosse matin et soir"),
    ("PEAU", "Elle recouvre tout le corps"),
    ("OS", "Il compose le squelette"),
    ("SANG", "Liquide rouge qui circule dans le corps"),
    # maison
    ("SALON", "Pièce où l'on reçoit les invités"),
    ("CHAMBRE", "Pièce où l'on dort"),
    ("TOIT", "Il protège la maison de la pluie"),
    ("MUR", "Il sépare deux pièces"),
    ("ESCALIER", "Il permet de monter à l'étage"),
    ("CLE", "Elle ouvre la porte"),
    ("MIROIR", "On s'y regarde"),
    ("LAMPE", "Elle éclaire la pièce"),
    ("TAPIS", "Il couvre le sol"),
    ("RIDEAU", "Il habille la fenêtre"),
    ("ARMOIRE", "On y range les vêtements"),
    ("CANAPE", "On s'y assoit pour regarder la télévision"),
    ("DOUCHE", "On s'y lave debout"),
    ("EVIER", "On y fait la vaisselle"),
    # nourriture
    ("POMME", "Fruit croquant, rouge ou vert"),
    ("POIRE", "Fruit à la peau fine et douce"),
    ("BANANE", "Fruit jaune et courbé"),
    ("RAISIN", "Petit fruit qui pousse en grappe"),
    ("FRAISE", "Petit fruit rouge en forme de cœur"),
    ("CITRON", "Fruit acide et jaune"),
    ("BEURRE", "On le tartine sur le pain"),
    ("FROMAGE", "Produit laitier affiné"),
    ("OEUF", "On le cuit au plat ou à la coque"),
    ("SUCRE", "Il rend les desserts doux"),
    ("SEL", "Il relève le goût des plats"),
    ("SOUPE", "Plat liquide et chaud"),
    ("GATEAU", "Dessert que l'on partage en fête"),
    ("VIANDE", "Chair d'animal que l'on cuisine"),
    ("LEGUME", "Carotte, poireau, ou courgette en sont"),
    ("CAFE", "Boisson chaude et corsée du matin"),
    ("THE", "Boisson infusée dans l'eau chaude"),
    ("LAIT", "Boisson blanche que l'on tire de la vache"),
    ("MIEL", "Produit sucré fabriqué par les abeilles"),
    ("PATE", "Base souple utilisée en cuisine ou en boulangerie"),
    # temps et nature
    ("PLUIE", "Elle tombe du ciel"),
    ("NEIGE", "Elle recouvre tout de blanc en hiver"),
    ("VENT", "Il fait bouger les feuilles"),
    ("GLACE", "Eau gelée, ou dessert froid"),
    ("CIEL", "Il est bleu le jour, noir la nuit"),
    ("MONDE", "L'ensemble de la Terre et de ses habitants"),
    ("TERRE", "Notre planète"),
    ("MER", "Grande étendue d'eau salée"),
    ("SABLE", "On en trouve sur la plage"),
    ("PIERRE", "Matériau dur trouvé dans la nature"),
    ("HERBE", "Elle pousse dans les prés"),
    ("FEUILLE", "Elle tombe des arbres en automne"),
    ("BRANCHE", "Elle porte les feuilles de l'arbre"),
    ("RACINE", "Elle ancre l'arbre dans le sol"),
    ("GRAINE", "Elle donne naissance à une plante"),
    # verbes courants
    ("ETRE", "Verbe d'existence, le plus utilisé en français"),
    ("AVOIR", "Verbe de possession"),
    ("ALLER", "Se déplacer vers un endroit"),
    ("VENIR", "Se déplacer vers celui qui parle"),
    ("VOIR", "Percevoir par les yeux"),
    ("SAVOIR", "Posséder une connaissance"),
    ("POUVOIR", "Avoir la capacité de faire quelque chose"),
    ("VOULOIR", "Désirer fortement"),
    ("DEVOIR", "Être obligé de faire quelque chose"),
    ("PRENDRE", "Saisir avec la main"),
    ("DONNER", "Remettre quelque chose à quelqu'un"),
    ("PARLER", "S'exprimer à voix haute"),
    ("ECOUTER", "Prêter attention à un son"),
    ("REGARDER", "Diriger son regard vers quelque chose"),
    ("MANGER", "Avaler de la nourriture"),
    ("BOIRE", "Avaler un liquide"),
    ("DORMIR", "Être plongé dans le sommeil"),
    ("MARCHER", "Se déplacer à pied"),
    ("CHANTER", "Produire de la musique avec la voix"),
    ("DANSER", "Bouger son corps en rythme"),
    ("TRAVAILLER", "Exercer une activité professionnelle"),
    ("APPRENDRE", "Acquérir une connaissance"),
    ("COMPRENDRE", "Saisir le sens de quelque chose"),
    ("CHERCHER", "Essayer de trouver quelque chose"),
    ("TROUVER", "Découvrir ce que l'on cherchait"),
    ("AIDER", "Apporter son soutien à quelqu'un"),
    ("AIMER", "Éprouver de l'affection"),
    ("ATTENDRE", "Rester en place jusqu'à un moment donné"),
    ("ARRIVER", "Parvenir à destination"),
    ("PARTIR", "Quitter un lieu"),
    # adjectifs et notions
    ("GRAND", "Contraire de petit"),
    ("PETIT", "Contraire de grand"),
    ("BEAU", "Agréable à regarder"),
    ("LAID", "Contraire de beau"),
    ("JEUNE", "Qui n'est pas vieux"),
    ("VIEUX", "Qui a beaucoup d'années"),
    ("RAPIDE", "Qui se déplace vite"),
    ("LENT", "Contraire de rapide"),
    ("FORT", "Qui a beaucoup de force"),
    ("FAIBLE", "Contraire de fort"),
    ("CHAUD", "Contraire de froid"),
    ("FROID", "Contraire de chaud"),
    ("LOURD", "Difficile à porter"),
    ("LEGER", "Facile à porter"),
    ("PROPRE", "Contraire de sale"),
    ("FACILE", "Qui ne demande pas d'effort"),
    ("DIFFICILE", "Qui demande beaucoup d'effort"),
    ("HEUREUX", "Qui ressent de la joie"),
    ("TRISTE", "Qui ressent de la peine"),
    ("CALME", "Sans agitation"),
    # vie quotidienne / notions
    ("TEMPS", "Il passe et ne revient jamais"),
    ("ANNEE", "Elle compte douze mois"),
    ("SEMAINE", "Elle compte sept jours"),
    ("HEURE", "Elle compte soixante minutes"),
    ("MATIN", "Début de la journée"),
    ("SOIR", "Fin de la journée"),
    ("NUIT", "Elle succède au jour"),
    ("FETE", "Moment de célébration et de joie"),
    ("CADEAU", "On l'offre pour faire plaisir"),
    ("ARGENT", "Il permet d'acheter"),
    ("TRAVAIL", "Activité exercée pour gagner sa vie"),
    ("ECOLE", "Lieu où l'on apprend"),
    ("VILLE", "Grande agglomération urbaine"),
    ("PAYS", "Territoire gouverné par un État"),
    ("LANGUE", "Elle sert à parler et à goûter"),
    ("MUSIQUE", "Art des sons organisés"),
    ("COULEUR", "Rouge, bleu ou vert en sont"),
    ("NOMBRE", "Il sert à compter"),
    ("SANTE", "Bon état du corps"),
    ("SECRET", "Ce que l'on garde caché"),
]
