# -*- coding: utf-8 -*-
# Banques de mots + indices, écrites à la main pour la preuve de concept.
# Format : (MOT, "Indice")

FACILE = [
    ("CHAT", "Compagnon domestique qui ronronne"),
    ("CHIEN", "Meilleur ami de l'homme"),
    ("PAIN", "On le coupe à table tous les jours"),
    ("EAU", "Elle coule à la source"),
    ("SOLEIL", "Il brille le jour"),
    ("LUNE", "Elle brille la nuit"),
    ("FLEUR", "Elle pousse dans le jardin"),
    ("ARBRE", "Il a des feuilles et des racines"),
    ("MAISON", "On y habite"),
    ("LIVRE", "On le lit page après page"),
    ("TABLE", "Meuble pour manger"),
    ("CHAISE", "On s'y assoit"),
    ("PORTE", "On l'ouvre pour entrer"),
    ("FENETRE", "On regarde dehors à travers elle"),
    ("JARDIN", "Coin vert avec des fleurs"),
    ("ROUTE", "Les voitures y roulent"),
]

MINI_5 = [
    ("LUNE", "Elle brille la nuit"),
    ("EAU", "Elle coule à la source"),
    ("NUIT", "Elle succède au jour"),
    ("UNE", "Article féminin singulier"),
    ("ANE", "Il porte les bagages du randonneur"),
    ("NEZ", "Il sent les odeurs"),
    ("LUI", "Pronom qui le désigne"),
    ("USE", "Il en fait trop, il ... sa santé"),
    ("EU", "Participe passé de avoir"),
    ("AN", "Une année, familièrement"),
]

MINI_8 = [
    ("SALADE", "On la prépare avec des légumes crus"),
    ("TERRE", "Notre planète"),
    ("CARTE", "On la consulte pour trouver son chemin"),
    ("ROSE", "Fleur au parfum délicat, ou couleur pastel"),
    ("RARE", "Qui ne se trouve pas facilement"),
    ("MERE", "Elle a donné la vie"),
    ("PERE", "Parent masculin"),
    ("LIRE", "Parcourir un texte des yeux"),
    ("DIRE", "Exprimer par la parole"),
    ("RIRE", "Manifester sa joie à voix haute"),
    ("TIRE", "Il ... la corde vers lui"),
    ("SIRE", "Titre donné à un souverain"),
    ("SEL", "Il relève le goût des plats"),
    ("MER", "Grande étendue d'eau salée"),
    ("LAC", "Étendue d'eau douce entourée de terre"),
    ("ETE", "Saison la plus chaude"),
    ("ARC", "Il lance des flèches"),
    ("RAT", "Petit rongeur des égouts"),
    ("TAS", "Amoncellement en désordre"),
    ("SOL", "On y pose les pieds"),
    ("DUR", "Difficile à supporter, ou peu tendre"),
    ("LIT", "Meuble où l'on dort"),
    ("RIZ", "Céréale de base en Asie"),
    ("CRI", "Son fort poussé par la voix"),
    ("SOLEIL", "Il brille le jour"),
    ("SIRENE", "Créature marine mi-femme mi-poisson"),
    ("SALE", "Contraire de propre"),
    ("SEUL", "Sans compagnie"),
    ("REEL", "Qui existe vraiment"),
]

MIDI_12 = [
    ("SALADE", "On la prépare avec des légumes crus"),
    ("TERRE", "Notre planète"),
    ("CARTE", "On la consulte pour trouver son chemin"),
    ("ROSE", "Fleur au parfum délicat, ou couleur pastel"),
    ("RARE", "Qui ne se trouve pas facilement"),
    ("MERE", "Elle a donné la vie"),
    ("PERE", "Parent masculin"),
    ("LIRE", "Parcourir un texte des yeux"),
    ("DIRE", "Exprimer par la parole"),
    ("RIRE", "Manifester sa joie à voix haute"),
    ("TIRE", "Il ... la corde vers lui"),
    ("SIRE", "Titre donné à un souverain"),
    ("SEL", "Il relève le goût des plats"),
    ("MER", "Grande étendue d'eau salée"),
    ("LAC", "Étendue d'eau douce entourée de terre"),
    ("ETE", "Saison la plus chaude"),
    ("ARC", "Il lance des flèches"),
    ("RAT", "Petit rongeur des égouts"),
    ("TAS", "Amoncellement en désordre"),
    ("SOL", "On y pose les pieds"),
    ("DUR", "Difficile à supporter, ou peu tendre"),
    ("LIT", "Meuble où l'on dort"),
    ("RIZ", "Céréale de base en Asie"),
    ("CRI", "Son fort poussé par la voix"),
    ("SOLEIL", "Il brille le jour"),
    ("SIRENE", "Créature marine mi-femme mi-poisson"),
    ("SALE", "Contraire de propre"),
    ("SEUL", "Sans compagnie"),
    ("REEL", "Qui existe vraiment"),
    ("SATELLITE", "Il orbite autour d'une planète"),
    ("LITTERAIRE", "Qui concerne les livres et l'écriture"),
    ("SOLITAIRE", "Qui vit ou agit seul"),
    ("RESTAURANT", "On y sert des repas contre paiement"),
    ("REALISATEUR", "Il dirige un film"),
    ("ARTISTE", "Il transforme une idée en œuvre"),
    ("SALAIRE", "Rémunération versée pour un travail"),
    ("RITUEL", "Cérémonie répétée selon un ordre précis"),
    ("SERIEUX", "Qui prend les choses au sérieux"),
]

_EXTRA_15 = [
    ("SILENCE", "Absence totale de bruit"),
    ("RECOLTE", "Fruit du travail des champs"),
    ("HORIZON", "Ligne où le ciel semble toucher la mer"),
    ("COURAGE", "Il permet d'affronter la peur"),
    ("TENDRESSE", "Douceur affectueuse envers autrui"),
    ("PATIENCE", "Vertu de celui qui sait attendre"),
    ("AMITIE", "Lien sincère entre deux personnes"),
    ("SAVEUR", "Ce que la langue reconnaît en premier"),
    ("TEXTURE", "Ce que les doigts perçoivent au toucher"),
    ("LIBERTE", "Elle n'a de prix pour personne"),
    ("VOLCAN", "Montagne qui gronde parfois de colère"),
    ("MEDECIN", "Il ausculte pour guérir"),
    ("GRENIER", "Sous les toits, royaume des souvenirs oubliés"),
    ("CURIOSITE", "Elle pousse à toujours vouloir savoir"),
]

# grille "difficile" 15x15 : la banque MIDI_12 enrichie de mots
# supplémentaires, en évitant les doublons entre les deux listes.
_midi_words = {w for w, _ in MIDI_12}
DENSE_15 = MIDI_12 + [entry for entry in _EXTRA_15 if entry[0] not in _midi_words]

MOYEN = [
    ("VOYAGE", "Déplacement vers une destination lointaine"),
    ("MUSIQUE", "Art des sons organisés"),
    ("LECTURE", "Activité que l'on fait avec un livre"),
    ("CUISINE", "Pièce où l'on prépare les repas"),
    ("HISTOIRE", "Récit du passé"),
    ("NATURE", "Ensemble du monde vivant et physique"),
    ("VOITURE", "Véhicule à quatre roues"),
    ("BUREAU", "Pièce ou meuble pour travailler"),
    ("JOURNAL", "Publication quotidienne d'actualités"),
    ("LUMIERE", "Elle chasse l'obscurité"),
    ("MONTAGNE", "Relief élevé qu'on peut escalader"),
    ("RIVIERE", "Cours d'eau qui rejoint un fleuve"),
    ("VILLAGE", "Petite agglomération à la campagne"),
    ("ETOILE", "Point lumineux dans le ciel nocturne"),
    ("PRINTEMPS", "Saison des fleurs"),
    ("AUTOMNE", "Saison des feuilles mortes"),
    ("HIVER", "Saison la plus froide"),
    ("ORAGE", "Pluie accompagnée de tonnerre"),
    ("NUAGE", "Il flotte dans le ciel avant la pluie"),
    ("FORET", "Grand ensemble d'arbres"),
    ("OCEAN", "Immense étendue d'eau salée"),
    ("DESERT", "Étendue de sable très sèche"),
    ("VOYELLE", "A, E, I, O, U en sont"),
    ("PHRASE", "Suite de mots avec un sens complet"),
    ("LETTRE", "Élément de l'alphabet, ou courrier"),
    ("ECOLE", "Lieu où l'on apprend"),
    ("JARDINIER", "Il s'occupe des plantes"),
]

DIFFICILE = [
    ("LABYRINTHE", "Dédale où l'on se perd facilement"),
    ("PARAPLUIE", "Objet indispensable un jour de pluie"),
    ("HORLOGE", "Elle égrène les heures sans jamais se lasser"),
    ("BIBLIOTHEQUE", "Temple silencieux du papier"),
    ("TELESCOPE", "Il rapproche les étoiles de nos yeux"),
    ("CHOCOLAT", "Péché mignon venu du cacao"),
    ("AEROPORT", "Porte d'entrée vers le ciel"),
    ("GRENIER", "Sous les toits, royaume des souvenirs oubliés"),
    ("CHEMINEE", "Elle réchauffe le salon en hiver"),
    ("ORCHESTRE", "Ensemble de musiciens qui joue à l'unisson"),
    ("VOLCAN", "Montagne qui gronde parfois de colère"),
    ("PYRAMIDE", "Tombeau pointu des pharaons"),
    ("GALAXIE", "Notre Voie lactée en est une"),
    ("ARCHITECTE", "Il dessine les bâtiments avant qu'ils existent"),
    ("MEDECIN", "Il ausculte pour guérir"),
    ("JARDINAGE", "Passe-temps qui salit les mains avec plaisir"),
    ("TEMPETE", "Colère du ciel et de la mer réunis"),
    ("LABOURER", "Retourner la terre avant de semer"),
    ("HORIZON", "Ligne où le ciel semble toucher la mer"),
    ("SILENCE", "Absence totale de bruit"),
    ("COURAGE", "Il permet d'affronter la peur"),
    ("PATIENCE", "Vertu de celui qui sait attendre"),
    ("GENEROSITE", "Elle pousse à donner sans compter"),
    ("CURIOSITE", "Elle pousse à toujours vouloir savoir"),
    ("TENDRESSE", "Douceur affectueuse envers autrui"),
    ("AMITIE", "Lien sincère entre deux personnes"),
    ("LIBERTE", "Elle n'a de prix pour personne"),
    ("VOYAGEUR", "Il a toujours une valise prête"),
    ("ARTISTE", "Il transforme une idée en œuvre"),
    ("INVENTEUR", "Il donne vie à ce qui n'existait pas"),
    ("HORTICULTEUR", "Spécialiste des fleurs et des plantes"),
    ("NAVIGATEUR", "Il trace sa route sur les mers"),
    ("ASTRONAUTE", "Il flotte loin de la Terre"),
    ("PHOTOGRAPHE", "Il fige un instant pour toujours"),
    ("ENSEIGNANT", "Il transmet le savoir chaque jour"),
    ("VOISINAGE", "Ensemble de ceux qui habitent tout près"),
    ("RECOLTE", "Fruit du travail des champs"),
    ("SAVEUR", "Ce que la langue reconnaît en premier"),
    ("TEXTURE", "Ce que les doigts perçoivent au toucher"),
    ("EQUILIBRE", "État stable que l'on cherche à garder"),
]
